swagger: '2.0'

info:
  description: 'API middleware that lets Hummingbot clients interact with standardized DEX API endpoints on various blockchain networks'
  version: '1.18.0'
  title: 'Hummingbot Gateway'
  license:
    name: 'Apache 2.0'
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'

host: 'localhost:15888'

tags:
  - name: 'system'
    description: 'System endpoints'
  - name: 'wallet'
    description: 'Wallet endpoints'
  - name: 'chain'
    description: 'Blockchain network endpoints'
  - name: 'amm'
    description: 'AMM DEX swap endpoints'
  - name: 'amm/liquidity'
    description: 'AMM DEX liquidity provision endpoints'
  - name: 'clob'
    description: 'CLOB spot DEX endpoints'
  - name: 'clob/perp'
    description: 'CLOB perpetual DEX endpoints'

schemes:
  - 'http'

externalDocs:
  description: 'Gateway Docs'
  url: 'https://hummingbot.org/gateway'
