certificatePath: /Users/feng/Code/hummingbot/certs/
logPath: ./logs
port: 15888
ipWhitelist: []
GMTOffset: 800
logToStdOut: true
unsafeDevModeWithHTTP: false
telemetry_enabled: false
nonceDbPath: nonce.level
transactionDbPath: transaction.level
id: b0e1946fcc4e8
